name: 'Assume Role For Environment'
description: 'Assume role for Environment'
inputs:
  aws-account:
    description: 'AWS account to assume CDCI role for'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps: 
    - name: Set AWS Role ARN for AWS account
      id: set-arn
      env:
        AWS_ACCOUNT: ${{ inputs.aws-account }}  # Map input to environment variable
      shell: bash
      run: |
        if [ "$AWS_ACCOUNT" == "biscred-dev" ]; then
            ROLE_ARN="arn:aws:iam::520831634247:role/CDCIDeployRole"
        elif [ "$AWS_ACCOUNT" == "biscred-prod" ]; then
            ROLE_ARN="arn:aws:iam::559114230719:role/CDCIDeployRole"
        elif [ "$AWS_ACCOUNT" == "bisnow" ]; then
            ROLE_ARN="arn:aws:iam::560285300220:role/CDCIDeployRole"
        elif [ "$AWS_ACCOUNT" == "vapor" ]; then
            ROLE_ARN="arn:aws:iam::844919361971:role/CDCIDeployRole"
        elif [ "$AWS_ACCOUNT" == "selectleaders" ]; then
            ROLE_ARN="arn:aws:iam::265833082685:role/CDCIDeployRole"
        else
            echo "Error: Invalid aws account specified" >&2
            exit 1
        fi

        echo "::set-output name=AWS_ROLE_ARN::$ROLE_ARN"

    - name: Assume github actions role
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        role-to-assume: arn:aws:iam::702073508373:role/GithubActions
        role-duration-seconds: 900
        aws-region: ${{ inputs.aws-region }}
        disable-retry: true

    - name: Assume biscred-dev deploy role with github actions role
      uses: aws-actions/configure-aws-credentials@v4
      with:  
        role-to-assume: ${{ steps.set-arn.outputs.AWS_ROLE_ARN }}
        aws-region: ${{ inputs.aws-region }}
        disable-retry: true
        role-chaining: true
